### ISSUE TITLE
Allow Float32 numbers or transform internally...

### ISSUE THREAD

**Issue by Datseris** [JuliaGeo/Proj.jl#39]
```
MethodError: no method matching transform!(::Projection, ::Projection, ::Array{Float32,1}, ::Array{Float32,1})
Closest candidates are:
  transform!(::Projection, ::Projection, ::Array{Float64,1}, ::Array{Float64,1}) at C:\Users\datse\.julia\packages\GeoMakie\xNXI6\src\projections.jl:46
  transform!(::Projection, ::Projection, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}; radians) at C:\Users\datse\.julia\packages\GeoMakie\xNXI6\src\projections.jl:46
```

is a typical message one gets when calling 
```
    Proj4.transform!(source, dest, vec(xs), vec(ys))
```
It makes little sense to me for everyone to transform all their data back and forth, instead of it happening here directly. (and In fact I have trouble understanding why this limitation of "only Float64" would exist in the first place)

**Comment by andyferris** [comment]
C binding to Proj are used so they only accept a fixed data type (and I believe Float64 precision is basically required inside some projection calls). 

Nonetheless a wrapper that automatically converts to/from any Real eltype would be a nice convenience.

**Comment by c42f** [comment]
Yes, `libproj` is a C library so there's really not much we can do about the fact that in-place transformations are only defined on `Float64`.  (By the way, for geographic coordinate systems, you'll often find that `Float32` is insufficient anyway — `eps(Float32(earth_radius))` is about 0.5 meter.)

Actually the new libproj C API (introduced in proj v5 or v6?) is quite different and I'm not sure it even supports batched transforms.

**Comment by Datseris** [comment]
> By the way, for geographic coordinate systems, you'll often find that Float32 is insufficient anyway 

for climate observational data Float32 is a standard though, because you cover the entire globe and since you have billions of points, the actual file size becomes more and more important. But anyway, the lowest level is not the deal-breaker here, its the highest.

**Comment by c42f** [comment]
Fair enough, I'm used to working with point cloud data where centimeter-level errors matter.

`transform!` for `Float32` would need to copy to a `Float64` buffer somewhere, do the transform and then copy back (at least in the old C API). It would be quite reasonable to offer that as a convenience function, and the implementation could use a batched mode to keep memory overhead low (though it would not be allocation-free).  So if someone wanted to implement that I imagine it would be fine.

Regardless of that, the old `transform` API is likely to be deprecated for the new Proj API at some stage soonish (https://github.com/JuliaGeo/Proj4.jl/pull/36#issuecomment-617723029), so that may render `transform` obsolete.

**Comment by Datseris** [comment]
I hope that there will be some minimal documentation with breaking changes / how to use the new interface, so that front end users don't suffer.

**Comment by visr** [comment]
Indeed PROJ always needs and returns Float64s. On master we accept other Reals as well that get converted to Float64 automatically, but the result will always be tuples of Float64s, so you'd have to convert back to Float32 yourself.
